export const PRODUCTS_REQUEST = 'PRODUCTS/REQUEST';
export const PRODUCTS_RECEIVE = 'PRODUCTS/RECEIVE';
export const PRODUCTS_RECEIVE_ERROR = 'PRODUCTS/ERROR';


// ADD TO CART
export const ADDTOCART_REQUEST = 'ADDTOCART/REQUEST';
export const ADDTOCART_RECEIVE = 'ADDTOCART/RECEIVE';
export const ADDTOCART_RECEIVE_ERROR = 'ADDTOCART/ERROR';

// Decrement
export const DECREMENT_REQUEST = 'DECRIMENT/REQUEST';
export const DECREMENT_RECEIVE = 'DECRIMENT/RECEIVE';
export const DECREMENT_RECEIVE_ERROR = 'DECRIMENT/ERROR';

// REMOVE FROM CART
export const REMOVEFROMCART_REQUEST = 'REMOVEFROMCART/REQUEST';
export const REMOVEFROMCART_RECEIVE = 'REMOVEFROMCART/RECEIVE';
export const REMOVEFROMCART_RECEIVE_ERROR = 'REMOVEFROMCART/ERROR'
